### ISSUE TITLE
Dmenu not using keyboard settings

### ISSUE THREAD

**Issue by R053NR07** [Evidlo/passhole#10]
Hey,

so I'm not sure if that's the same issue like #7 but I'm having trouble with the standard dmenu behavior of passhole. It simply ignores my keyboard settings and outputs the username/password with us keyboard settings. This messes up a lot of characters. 

You mentioned the pynput branch so I tried it out: works fine. 

So is there a plan to merge pynput to master to get rid of this issue?

Thanks for your work!

Edit: Sorry pynput does also not work fine. Some characters now are right, many special characters are still wrong.

Edit2: So i tried it again: pynput gives me the right pws with normal type mode. In tabbed mode the password special chars get mixed up.

Edit3: It works for me when reinitializing the keyboard controller for the password (after typing the username). Somehow it seams the tab press messes up the controller... I don't know why.

Edit4: Seems to be some kind of timing issue. When not reinitializing the controller it works when doing a sleep(0.06). With a sleep less the value the chars get mixed up after the tab press.

**Comment by Evidlo** [comment]
Have you tried `--xdotool` already?

**Comment by R053NR07** [comment]
Yes. Same problem with xdotool. I even need a higher timeout for xdotool to work. Xdotool was also inconsistent for me. If I typed fast the result was more likely messed up. I really don't know why typing speed should have impact on the output.

**Comment by Evidlo** [comment]
I don't understand the problem.  Can you replicate this with a barebones python script that calls PyKeyboard?

**Comment by R053NR07** [comment]
Yes I can:

```
from pykeyboard import PyKeyboard
import time

time.sleep(5)
k = PyKeyboard()
k.type_string('blablabla')
k.tap_key(k.tab_key)
k.type_string('some_pass_$!+')
```

outputs: `blablabla    some?pass?$!)`

My locale settings:
`
   System Locale: LANG=en_US.UTF-8
       VC Keymap: sg
       X11 Layout: ch
`

I can print the right password by doing:
```
from pykeyboard import PyKeyboard

k = PyKeyboard()
k.type_string('blablabla')
k.tap_key(k.tab_key)

del k
k = PyKeyboard()
k.type_string('some_pass_$!+')
```

**Comment by R053NR07** [comment]
Nope still `blablabla    some?pass?\}!`

**Comment by Evidlo** [comment]
I still can't reproduce what you're seeing:

```
[evan@blackbox ~] localectl set-keymap sg
[evan@blackbox ~] localectl status
   System Locale: LANG=en_US.UTF-8
       VC Keymap: sg
      X11 Layout: ch
       X11 Model: pc105
     X11 Variant: de_nodeadkeys
     X11 Options: terminate:ctrl_alt_bksp

[evan@blackbox ~] ipython3
In [1]: from pynput.keyboard import Key, Controller
   ...: import time
   ...: 
   ...: time.sleep(2)
   ...: k = Controller()
   ...: k.type('blablabla')
   ...: k.press(Key.tab)
   ...: k.release(Key.tab)
   ...: k.type('some_pass_$!+')
   ...: 
   ...: 
blablabla	some_pass_$!+

```

**Comment by R053NR07** [comment]
Thats strange. Maybe just close the ticket if no one else has this Problem and it's not really the fault of passhole. (And I hacked in the solution for me)
