### ISSUE TITLE
Support for multiple databases

### ISSUE THREAD

**Issue by varac** [Evidlo/passhole#15]
It would be awesome if `passhole` could support multiple databases like [gopass can handle multiple password stores](https://github.com/gopasspw/gopass/blob/master/docs/features.md#multiple-stores) (or [keepmenu](https://github.com/firecat53/keepmenu) does).

**Comment by Evidlo** [comment]
Try the `multi_database` branch and let me know what you think.

**Comment by varac** [comment]
Great, will do!
