### ISSUE TITLE
ph init error

### ISSUE THREAD

**Issue by gmoneymagna** [Evidlo/passhole#17]
Hey thanks for making this, I'm really excited to use it.

I am unable to ph init after install. I'm using Manjaro i3. I installed gpg-crypter from Pacman. I can't locate a package libgpgme-dev in pacman, yaourt or pip like the install page says. Do you have any ideas, or how to locate libgpgme-dev?

Thanks!

**Comment by Evidlo** [comment]
What about [gpgme](https://www.archlinux.org/packages/core/x86_64/gpgme/files/).

**Comment by gmoneymagna** [comment]
I have installed yaourt gpgme 1.12.0-2 (A C wrapper for library GnuPG) and python-gpgme 1.12.0-2 (python bindings for GPGme). I can try to install the 3rd option, gpgme 1.12.0-2 (Qt bindings for GPGme).

**Comment by Evidlo** [comment]
I made a stupid mistake with the most recent release, so just use version 1.7.7 for now.  Thanks for reporting.

``` bash
pip install passhole==1.7.7
```

**Comment by Evidlo** [comment]
I added some information to the README about installing on arch.  Also I've released version 1.8.2 which fixes the installation issue.
