### ISSUE TITLE
Missing dependency description.

### ISSUE THREAD

**Issue by hThoreau** [Evidlo/passhole#18]
Hello there. I've just installed passhole. But following a different installation that the one described in the README: Besides installing `libgpgme-dev`, I've installed `python3-dev`, `libxslt-dev`, `libxml2-dev` and eventually installed passhole using python 3 - `pip3 install passhole==1.7.7 --user`.

That's it, just a heads-up. Thanks for your amazing work.

**Comment by Evidlo** [comment]
I added some information for Debian, Fedora and Arch to the readme.
