### ISSUE TITLE
Feature Request: Support to TOTP generator

### ISSUE THREAD

**Issue by baco** [Evidlo/passhole#22]
It would be great if `passhole` supports the storage and retrieval of TOTP (Timed One-Time Passwords) like [KeePassXC has](https://keepassxc.org/project/#features)

**Comment by baco** [comment]
For example, KeePassXC via it's _cli_, has the flag `-t` for the `show` command that uses the fields: `TOTP Seed` and `TOTP Settings` to compute the One-Time password.

**Comment by Evidlo** [comment]
Closed by https://github.com/Evidlo/passhole/pull/49
