### ISSUE TITLE
Add edit option for root group

### ISSUE THREAD

**Issue by baco** [Evidlo/passhole#23]
The root group has a strange name `blank` that comes from the template database `blank.kdbx`. Add at least an option to edit also that group-name for when the database file is opened by other password manager.

**Comment by Evidlo** [comment]
I extended `edit` to work for groups in this branch: https://github.com/Evidlo/passhole/tree/editroot

Let me know what you think.

**Comment by baco** [comment]
ok, but at the moment, there is no display of the root group `blank`, I can see it when I use my keepass file on other client. So there is no way I can edit it because running `passhole edit blank/` assumes I am trying to edit a group blank **inside** the root group `blank`

**Comment by Evidlo** [comment]
`ph edit /`

**Comment by baco** [comment]
ok, let me try it and I tell you

**Comment by baco** [comment]
works perfectly!

Do you close the issue on merging to master or right now?

**Comment by Evidlo** [comment]
It's merged.
