### ISSUE TITLE
Bug: It is possible to add the same entry name more than once

### ISSUE THREAD

**Issue by baco** [Evidlo/passhole#24]
It is possible to execute `passhole add entry-name` more than once (because internally have different UUIDs), butwhen trying to retrieve it back, there is no way to retrieve all the entries with the same name or to choose which one to `show`.

**Comment by Evidlo** [comment]
Can you explain what you mean?  The `add` command checks whether the entry exists before creation:

```
[evan@blackbox ~] ph add entry-name -w
Username: lkj
URL: lkj
[evan@blackbox ~] ph grep entry
[passhole] (default)
entry-name
[evan@blackbox ~] ph add entry-name -w
There is already an entry at entry-name
```

**Comment by baco** [comment]
for instance, I was able to do 2 times `passhole add lola` with different values each time:

```
% ~/.local/bin/passhole ls      
Enter password (root): 
@root (default)
github
lola
lola
la
personal
└── gitlab
```

and when I try to show them, only the first one is retrieved:

```
passhole show lola 
Enter password (root): 
Title: lola
Username: 
Password: 
URL:
```

(the other entry has some values)

**Comment by Evidlo** [comment]
`show` only working for the first entry is the intended behavior. 

 However, `add` should definitely give an error if you add `lola` twice

```
[evan@blackbox ~] passhole add lola
Username: foo
Password: 
Confirm: 
URL: foo
[evan@blackbox ~] passhole add lola
There is already an entry at lola
```

**Comment by baco** [comment]
Ok, tried it, now it does give an error. But now I have clone from the branch I need to test for editing root group. Before I was using PIP's version. Perhaps a fix that came in the middle?

**Comment by Evidlo** [comment]
I was also testing on the version from pypi.
