### ISSUE TITLE
Retrieving only one entry asks to unlock all the databases

### ISSUE THREAD

**Issue by baco** [Evidlo/passhole#25]
When trying to retrieve only one entry in a specific database asks for the password to unlock all the databases:

```
$ passhole show @root/lola
Enter password (root): 
Enter password (lala): 
Title: lola
Username: 
Password: 
URL: 
```

Only asking for the specific database's password would be expected.

**Comment by Evidlo** [comment]
This should be fixed in master.  Let me know what you think.
