### ISSUE TITLE
Feature request - case insensitive setting

### ISSUE THREAD

**Issue by ReneFroger** [Evidlo/passhole#28]
I have the following order for password: `Work/Foo/Bar`
When I type in passhole's Dmenu 

    foo bar

He found nothing, so I need to check the uppercases everytime when I want to grab the password.
Could case insensitive behaviour be set with, for example: `ph type dmenu --insensitivecase` ?

**Comment by Evidlo** [comment]
This is a feature of `dmenu`, not passhole.  `dmenu` already has a case insensitive option `-i`.

Also, as of version `1.9`, the syntax to the type command has changed: `ph type --prog 'dmenu -i'`

**Comment by ReneFroger** [comment]
Thanks for your reply. The command in my i3 config is not working with:

    bindsym Mod1+p exec "ph type --prog 'dmenu -i'"

But it's working only With

    bindsym Mod1+p exec "ph type dmenu"

 With version 1.9, are you referring to Passhole, I assume? If so, where could I get the binary of that? Since the releases list of passhole doesn't go further than version 1.5

**Comment by Evidlo** [comment]
Didn't you say in the other issue that you are already running 1.9?

What happens if you run `ph type --prog 'dmenu -i'` in the shell.

**Comment by ReneFroger** [comment]
Yes, I'm running `ph 1.9.post1` that I have installed via pip3 on Ubuntu 18.04.1 LTS.

The output when I'm trying your suggestion to type `ph type --prog 'dmenu -i` in the shell: 
```
$ ph -v
1.9.post1
$ ph type --prog 'dmenu -i'
usage: ph [-h] [--debug] [--database PATH] [--keyfile PATH] [--no-password]
          [--gpgkey FINGERPRINT] [--config PATH] [-v]
          {show,type,add,remove,rm,edit,move,mv,list,ls,grep,init,dump} ...
ph: error: unrecognized arguments: --prog
```

**Comment by Evidlo** [comment]
Try the latest version from pypi, 1.9.post2.

**Comment by ReneFroger** [comment]
Thanks for your help.

I just upgraded passhole with `sudo pip install passhole --upgrade`, since I noticed there was 1.9.post2 on Python Package Index released just a hour ago 

Then the command is working smooth without any issues. Many thanks for your help, it's really appreciated! This issue can be considered as solved. Closed now :)
