### ISSUE TITLE
Installation of passhole without prompting to give database a name 

### ISSUE THREAD

**Issue by ReneFroger** [Evidlo/passhole#30]
I have the following script to automate the installation of Passhole:

```
# Passhole
sudo -H pip3 install passhole
# After synchronisation, link passhole configuration
sudo /bin/rm -f /home/user/.local/passhole
sudo mkdir -vp /home/user/.local/passhole
sudo ln -sfvn /home/user/Dropbox/Dot/.local/passhole/passhole.kdbx /home/user/.local/passhole/passhole.kdbx
ph --database /home/user/.local/passhole/passhole.kdbx init
```

The latest commands ask me everytime to give the database a name. I looked in the documentation to give a name in the flag parameter, but I couldn't find anything relevant.

I tried the following:
```
echo "passhole" | ph --database /home/user/.local/passhole/passhole.kdbx init
```
but it's causing problems when he is trying to reading that line. Is there any way to prevent that being asked, to include passhole in an unattended installation of all packages?

**Comment by ReneFroger** [comment]
Another way is to solve this issue with modifying the function that reads the line of database name: https://stackoverflow.com/questions/55158841/stop-script-eoferror-eof-when-reading-a-line

**Comment by Evidlo** [comment]
Can you give me some background?  Why are you trying to automate initialization?

**Comment by ReneFroger** [comment]
Because I use the same setup on multiple laptops, my whole `.config` folder is synchronized with Dropbox. I wrote a bash script that installs all the packages in once, without attending. It's helpful, because sometimes I mess my setup up.

**Comment by Evidlo** [comment]
This should be fixed with https://github.com/Evidlo/passhole/commit/efb6187feb2ee41091ed73a47c9ad9480c872837.

Let me know what you think.
