### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by freijon** [Evidlo/passhole#33]
Passhole was exactly what I was looking for. Unfortunately on wayland the "type" feature doesn't work. I can imagine that to be quite difficult... As a workaround a "copy password to clipboard" feature would be nice with the ability to use whatever clipboard tool defined. It could work similar to "type PROG", but with "copy PROG".

**Comment by Evidlo** [comment]
Need to find a cross-platform clipboard library first.  Pyperclip looks good, but doesn't support Wayland yet.

**Comment by freijon** [comment]
Just found out there is an app called [wlrctl ](https://git.sr.ht/~brocellous/wlrctl) which can be used to type using a virtual keyboard. Maybe this could be used?

**Comment by Evidlo** [comment]
There's also ydotool, but that requires root.

**Comment by Evidlo** [comment]
@freijon How does typing tabbed characters work in wlrctl?

I may just change the `--xodotool` argument into a `--cmd CMD` argument that takes the stuff to type on its stdin.

**Comment by Evidlo** [comment]
So it seems like pynput should support Wayland now, but I haven't tested it.

**Comment by Evidlo** [comment]
Everything seems to be working in Sway/Wayland.

**Comment by seidler2547** [comment]
I don't know if I'm doing something wrong, but it doesn't work for me on Wayland (sway). I have tried various "choosers" like rofi, wofi and yofi, and all of them get the correct result back to ph, but there's no output:
```
[sei@pc ~]$ ph --debug type 
Debugging enabled...
reading config from /home/sei/.config/passhole.ini
default_section km
opened databases:{'/home/sei/.passhole.kdbx': <pykeepass.pykeepass.PyKeePass object at 0x7f67df9ebe50>}
opening /home/sei/.passhole.kdbx from cache
text from dmenu: Amazon/AWS Management Console
selected_entry:Entry: "Amazon/AWS Management Console (xx@xxx.com)"
[sei@pc ~]$
```
