### ISSUE TITLE
pkg_resources.DistributionNotFound

### ISSUE THREAD

**Issue by freijon** [Evidlo/passhole#34]
When trying to use release version 1.9.2 I get the following error:
`pkg_resources.DistributionNotFound: The 'pykeepass_cache' distribution was not found and is required by passhole` even though pykeepass (3.2.0) is installed...

**Comment by Evidlo** [comment]
Not sure why this is happening.  You can try `pip install pykeepass-cache` to manually install that dependency.

**Comment by PRESFIL** [comment]
I have similar issue:

```sh
Traceback (most recent call last):
  File "/usr/bin/passhole", line 33, in <module>
    sys.exit(load_entry_point('passhole==1.9.2', 'console_scripts', 'passhole')())
  File "/usr/lib/python3.8/site-packages/passhole/passhole.py", line 1020, in main
    args.func(args)
  File "/usr/lib/python3.8/site-packages/passhole/passhole.py", line 488, in type_entries
    databases = open_database(all=True, **vars(args))
  File "/usr/lib/python3.8/site-packages/passhole/passhole.py", line 294, in open_database
    from pykeepass_cache.pykeepass_cache import PyKeePass, cached_databases
ModuleNotFoundError: No module named 'pykeepass_cache'
```

In my case it is maintainer fault - package from **AUR** have not `pykeepass-cache` dependency (because this package does not exists). @freijon, which OS distribution do you use?

**Comment by freijon** [comment]
I created an ebuild for Gentoo, but I took inspiration from the AUR package to see what the dependencies were. From the error message I assumed the issue is with `pykeepass`, I didn't know that `pykeepass_cache` is a seperate package. Anyway, to be honest, I gave up on trying to get this working...

**Comment by PRESFIL** [comment]
I think that there must be separate package, because for `pip` it is separate:

```
$  pip search pykeepass-cache
pykeepass-cache (3)              - database caching for PyKeePass
pykeepass (3.2.1)                - Python library to interact with keepass databases (supports KDBX3 and
```

but, no one needs it, so it is not in the **AUR**, nor in *source tree*.

**Comment by PRESFIL** [comment]
This has been [fixed][1]. You can try to find same dependencies alternatives in Gentoo package base.

[1]: https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=passhole&id=82a9d111432049b69bc58314bd964cc40028b77a

**Comment by Evidlo** [comment]
If this is a big enough problem, I can move the import statement so the module is only imported if caching is used.
