### ISSUE TITLE
Feature request: XDG conformance: moving .local/passhole -> .local/share/passhole/

### ISSUE THREAD

**Issue by PRESFIL** [Evidlo/passhole#36]
Is there any reason for storing default *passhole-database* in ` .local/passhole/`? If no, can you change it to `.local/share/passhole/`?

**Comment by Evidlo** [comment]
Fixed in https://github.com/Evidlo/passhole/commit/1c352f47282dfe05b64a7b5aeb78d0b3e5e955ac

Should probably also check if `$XDG_CONFIG_HOME` and `$XDG_DATA_HOME` are set, at some point.
