### ISSUE TITLE
Use `sys.exit(1)` on error

### ISSUE THREAD

**Issue by ulken** [Evidlo/passhole#41]
Unless I'm missing something, I think you should use `sys.exit(1)` instead of `sys.exit()` (with an implicit exit code of `0`) whenever the program exists abnormally (i.e. with an error).

This would be especially helpful in custom scripts around `passhole`.

In the meantime, I resolved to parsing the output, but it feels kinda dirty/hacky.

Thoughts?

**Comment by Evidlo** [comment]
Seems entirely reasonable.  I will accept a PR if you want to implement the change.

**Comment by ulken** [comment]
@Evidlo ☝️
