### ISSUE TITLE
Piping/subshell and tty

### ISSUE THREAD

**Issue by ulken** [Evidlo/passhole#43]
I'm trying to add a function around `ph` for copying a password to the clipboard.

However, since the db is password-protected, it prompts me for the password (unless cached). That's fine and expected, but it also means I can't pipe the output to the clipboard. Neither can I run the command in a subshell since it's not considered a TTY.

I don't want to print it to stdout.

Any thoughts how I might go about this? Could we add an explicit `login` command? Could we allow passing password as an option (guessing you deliberately chose to not do that)?

Might not make any difference, but do we really care about `stdout` being a TTY? Isn't `stdin` more relevant? But maybe they always have the same value?

Thankful for input 🙏

**Comment by Evidlo** [comment]
> That's fine and expected, but it also means I can't pipe the output to the clipboard.

Why not?  It should invoke zenity for prompting the password when it detects a TTY.

> Might not make any difference, but do we really care about stdout being a TTY? Isn't stdin more relevant? But maybe they always have the same value?

Checking stdin makes more sense.  I've changed it to do so with the latest commit.

**Comment by ulken** [comment]
> Why not? It should invoke zenity for prompting the password when it detects a TTY.

I'm on macOS and only use `ph` from the command line. I'd rather not install/rely on `zenity`.

**Comment by Evidlo** [comment]
Well it doesn't check stdout anymore, so this should work for you now.

**Comment by ulken** [comment]
Works perfectly, thanks!
