### ISSUE TITLE
"ph type" gives "TypeError: unhashable type: 'list'"

### ISSUE THREAD

**Issue by seidler2547** [Evidlo/passhole#48]
Using passhole 3.2.1-1 from AUR and while `ph list` works fine, `ph type` gives this error:
```
$ ph type
Traceback (most recent call last):
  File "/usr/bin/ph", line 33, in <module>
    sys.exit(load_entry_point('passhole==1.9.4', 'console_scripts', 'ph')())
  File "/usr/lib/python3.9/site-packages/passhole/passhole.py", line 1049, in main
    args.func(args)
  File "/usr/lib/python3.9/site-packages/passhole/passhole.py", line 511, in type_entries
    entry_texts[entry_text] = kp
  File "/usr/lib/python3.9/site-packages/rpyc/core/netref.py", line 185, in __hash__
    return syncreq(self, consts.HANDLE_HASH)
  File "/usr/lib/python3.9/site-packages/rpyc/core/netref.py", line 76, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/usr/lib/python3.9/site-packages/rpyc/core/protocol.py", line 469, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/usr/lib/python3.9/site-packages/rpyc/core/async_.py", line 102, in value
    raise self._obj
TypeError: unhashable type: 'list'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/rpyc/core/protocol.py", line 320, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/lib/python3.9/site-packages/rpyc/core/protocol.py", line 590, in _handle_hash
    return hash(obj)
TypeError: unhashable type: 'list'
```

Unfortunately I have no idea where to start debugging this.

**Comment by Evidlo** [comment]
Can you try using passhole from pip?

**Comment by seidler2547** [comment]
Yes it does after installing 1.9.5 using pip. It seems that there is some confusion (at least on my part) about the versioning. Somehow I had 1.9.4 installed, so I don't quite understand why there is a 1.x release series and a 3.x release series?

**Comment by Evidlo** [comment]
That looks like an old version number from [pykeepass](https://github.com/libkeepass/pykeepass), so the AUR maintainer might have made a mistake.

**Comment by seidler2547** [comment]
> That looks like an old version number from [pykeepass](https://github.com/libkeepass/pykeepass), so the AUR maintainer might have made a mistake.

I think the maintainer took [this tag](https://github.com/Evidlo/passhole/releases/tag/v3.2.1) and packaged it.

**Comment by PRESFIL** [comment]
I took over this requested PKGBUILD. How can I help?

In general, it is very strange that this PKGBUILD targets a [fork of that repository](https://github.com/pschmitt/pykeepass), no an [original](https://github.com/libkeepass/pykeepass), which is very strange. And the versions there lag behind the original.

**Comment by seidler2547** [comment]
@PRESFIL I commented on the AUR package, thanks for being the maintainer.

@Evidlo to my untrained eye it looks like the tag 3.2.1 on this repo doesn't really fit. If so, and if it is possible to delete tags, would that be an option?

**Comment by PRESFIL** [comment]
OK, now I understand. This tashg does not exist now and this is the most important issue at the moment. I'll fix that.

The next thing I noticed is that the [python-pykeepass-git](https://aur.archlinux.org/packages/python-pykeepass-git/) is aimed at some fork. Apparently he previously listened for some kind of interim fix, but now he is out of upstream and has already fulfilled his role. I think this needs to be fixed (I also support this package now :smiley: ).

**Comment by Evidlo** [comment]
My mistake.  I just deleted the 3.2.1 tag.

`pschmitt/pykeepass` was the original location of the project, but it has since moved to `libkeepass/pykeepass`.

**Comment by PRESFIL** [comment]
I have updated the package opba. Hopefully this will not create new problems, and will solve those in this thread.
