### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by azinsharaf** [Evidlo/passhole#52]
Hi, I have to use `ph` in Windows. Would it be supported in that env? I am getting `no module named readline` error.

**Comment by Evidlo** [comment]
As of right now, it's not technically supported since GNU readline doesn't exist on Windows.  However you should be able to hack it in pretty easily.

Just delete the `import readline` at the top of `passhole.py`, then change the `editable_input()` function to this:


``` python
def editable_input(prompt, prefill=None):
    return input(prompt + ': ')
```

**Comment by azinsharaf** [comment]
Thank you @Evidlo. Good workaround.

**Comment by azinsharaf** [comment]
FYI, I installed WSL (Ubuntu) on my window machine recently and I'm able to use passhole in that env. No Win headache.

**Comment by Evidlo** [comment]
@approximate Sorry for the slow response.  You might try with the `--no-cache` option, as I'm guessing the error is being thrown inside `pykeepass_cache`.

`python-daemon` is just used to run the cache server in the background.  There might be a more cross-platform way to achieve this though: https://stackoverflow.com/questions/1196074/start-a-background-process-in-python
