### ISSUE TITLE
using grep to copy pw

### ISSUE THREAD

**Issue by azinsharaf** [Evidlo/passhole#57]
Hi, 
How can i copy the username or password of an entry returned by `ph grep`  into clipboard? For instance in `kpcli` app it returns an index for each entry and we can use `show <index>` , `xp <index>` , etc. 

```
$ ph --config /home/azin/.config/passhole/passhole.ini grep jn2

GIS_Admin/Database/JN2595001_Glenborough/jn2595001_admin
GIS_Admin/Database/JN2595001_Glenborough/jn2595001_writer
GIS_Admin/Database/JN2595001_Glenborough/jn2595001_reader
```

**Comment by Evidlo** [comment]
I haven't used kpcli, but `grep` returns the path to the entry, so you should just be able to `show PATH`.

```
ph show $(ph grep test | head) --field username | xclip -i
```

**Comment by azinsharaf** [comment]
Thanks @Evidlo. This works but is there any faster way to do it? Just too much typing to get the pw of an entry. I see you have some i3wm key binding but i don't have i3wm on my Ubuntu (WSL). Does it make things easier?

**Comment by Evidlo** [comment]
Why do you want to interactively copy a user/password into the clipboard?  If you just want to paste them into a form on a website, that's what the `type` command is for.

**Comment by azinsharaf** [comment]
can you please give me an example how to use `type` command? I need to copy password and paste it in either a website or window.

**Comment by Evidlo** [comment]
The keybinding in the README is just an example for i3, but it should work for any window manager.

**Comment by azinsharaf** [comment]
Thanks. I check it out.
