### ISSUE TITLE
`passhole init` will overwrite databases when given homedirectory-relative paths

### ISSUE THREAD

**Issue by Alch-Emi** [Evidlo/passhole#63]
## Steps to Recreate
(on linux, at least)

1. Create or find an arbitrary file to destroy
2. Run `ph init`
3. When prompted for a name, give any unused database name
4. Provide a valid path to the file using a `~`, for example `~/Desktop/sacrifice.kdbx`
5. Proceed through the prompts as usual
6. Once finished, check in on your original file to find that it has been obliterated

## Solution(s)

I think this should be as simple as hitting the path with [`os.path.expanduser()`](https://docs.python.org/3.8/library/os.path.html#os.path.expanduser) before checking its existence.  I experienced this issue with the database, but skimming the source code, it looks like a similar issue might exist for the keyfile as well.  It might be a good idea to [open the keyfile](https://github.com/Evidlo/passhole/blob/e493253b484becd16c59189e85b3ace482a1668a/passhole/passhole.py#L282) with the mode `x` (e**x**clusive creation) instead of just `w`, so that the OS will refuse to overwrite a pre-existing keyfile even if the safeguards fail, although I don't think this will work for the database.

**Comment by Evidlo** [comment]
Thanks, should be fixed in https://github.com/Evidlo/passhole/commit/3bcca298d21e4534ef2663df4a94a48b3c4375cf
